package BP2_1821221018_Halis_FurkanAkgulOdev1;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class SiparisAlani extends javax.swing.JFrame {

    Ekullanici kullanici;
    DefaultListModel dlm = new DefaultListModel();
    DefaultTableModel dtm = new DefaultTableModel();
    int id;
    int id2;
    int toplamTutar = 0;
   

    public SiparisAlani(Ekullanici a) {
        initComponents();
        kullanici = a;
        dtm.setColumnIdentifiers(new String[]{"TÜR", "RENK", "FİYAT", "KATEGORİ", "DURUM", "MALZEME"});
        cicekTablosu.setModel(dtm);
        this.id = kullanici.getId();
        ekle.setEnabled(false);
        sil.setEnabled(false);
        siparisListesi.setModel(dlm);
    }

    public SiparisAlani(Ekullanici a, ArrayList<Cicek> arr, ArrayList<Integer> arry, int t) {
        initComponents();
        for (int i = 0; i < arr.size(); i++) {
            siparis.add(arr.get(i));
        }
        for (int i = 0; i < arry.size(); i++) {
            adetler.add(arry.get(i));
        }
        toplamTutar=t;
        kullanici = a;
        dtm.setColumnIdentifiers(new String[]{"TÜR", "RENK", "FİYAT", "KATEGORİ", "DURUM", "MALZEME"});
        this.id = kullanici.getId();
        yeniSiparis();
        ekle.setEnabled(false);
        sil.setEnabled(false);

    }

    public SiparisAlani() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cicekTablosu = new javax.swing.JTable();
        hepsiniListele = new javax.swing.JButton();
        kategoriler = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        siparisListesi = new javax.swing.JList<>();
        ekle = new javax.swing.JButton();
        adet = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tutarEkran = new javax.swing.JTextField();
        sil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        siparisYonetimi = new javax.swing.JButton();
        çıkış = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cicekTablosu.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cicekTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TÜR", "RENK", "FİYAT", "KATEGORİ", "DURUM", "MALZEME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cicekTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cicekTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cicekTablosu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 530, 136));

        hepsiniListele.setBackground(new java.awt.Color(51, 204, 255));
        hepsiniListele.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hepsiniListele.setText("Hepsini Listele");
        hepsiniListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hepsiniListeleActionPerformed(evt);
            }
        });
        jPanel1.add(hepsiniListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, -1));

        kategoriler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kategoriler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hediye", "Kutlama", "Taziye", "Tebrik", "Yılbaşı", "Terfi", "Dekoratif", "Düğün" }));
        kategoriler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategorilerActionPerformed(evt);
            }
        });
        jPanel1.add(kategoriler, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 140, -1));

        siparisListesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siparisListesiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(siparisListesi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 150));

        ekle.setBackground(new java.awt.Color(255, 255, 153));
        ekle.setText("EKLE");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });
        jPanel1.add(ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 100, -1));

        adet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jPanel1.add(adet, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 40, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ADET : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 50, 20));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("TUTAR :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 90, -1));
        jPanel1.add(tutarEkran, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 110, -1));

        sil.setBackground(new java.awt.Color(255, 102, 102));
        sil.setText("SİL");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        jPanel1.add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BP2_1821221018_Halis_FurkanAkgulOdev1/icon/cicek-satis-1_210x90.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 210, 90));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jLabel1.setText("ÇİÇEK LİSTESİ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        siparisYonetimi.setBackground(new java.awt.Color(51, 255, 0));
        siparisYonetimi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        siparisYonetimi.setText("SİPARİŞ SEPETİ");
        siparisYonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisYonetimiActionPerformed(evt);
            }
        });

        çıkış.setBackground(new java.awt.Color(204, 0, 0));
        çıkış.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        çıkış.setText("ÇIKIŞ YAP");
        çıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çıkışActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BP2_1821221018_Halis_FurkanAkgulOdev1/icon/unnamed_135x68.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(çıkış, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siparisYonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siparisYonetimi)
                    .addComponent(çıkış))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Cicek> cicekler = new ArrayList();
    public ArrayList<Cicek> siparis = new ArrayList();
    public ArrayList<Integer> adetler = new ArrayList();
    public void doldur() {
        cicekler.add(new Cicek("Gül", "Kırmızı", 15, "Hediye"));
        cicekler.add(new Cicek("Gül", "Beyaz", 18, "Hediye"));
        cicekler.add(new Cicek("Lale", "Sarı", 25, "Hediye"));

        cicekler.add(new Cicek("Çelenk", "Yeşil", 120, "Kutlama"));
        cicekler.add(new Cicek("Çelenk", "Siyah", 120, "Taziye"));

        cicekler.add(new Cicek("Orkide", "Beyaz", 90, "Tebrik"));
        cicekler.add(new Cicek("Orkide", "Sarı", 90, "Tebrik"));

        cicekler.add(new Cicek("Tereryum", "Yeşil", 150, "Yılbaşı"));
        cicekler.add(new Cicek("Tereryum", "Mavi", 160, "Yılbaşı"));

        cicekler.add(new Cicek("Leylak", "Pembe", 16, "Terfi"));
        cicekler.add(new Cicek("Menekşe", "Mor", 29, "Terfi"));

        cicekler.add(new Cicek("Fesleğen", "Yeşil", 35, "Dekoratif"));
        cicekler.add(new Cicek("Sarmaşık", "Yeşil", 125, "Dekoratif"));

        cicekler.add(new CansizCicek("Buket", "Beyaz", 250, "Düğün", "Kumaş"));
        cicekler.add(new CansizCicek("Lale", "Eflatun", 10, "Hediye", "Latex"));
        cicekler.add(new CansizCicek("Sümbül", "Mor", 27, "Kutlama", "Plastik"));
        cicekler.add(new CansizCicek("Zambak", "Kırmızı", 35, "Düğün", "Kumaş"));
    }

    public void yeniSiparis() {
        dlm.removeAllElements();
        for (Cicek c : siparis) {
            dlm.addElement(adetler.get(siparis.indexOf(c)) + " adet " + c.getRenk() + " " + c.getTür());
        }
        siparisListesi.setModel(dlm);
        tutarEkran.setText(toplamTutar + "");
    }


    private void hepsiniListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hepsiniListeleActionPerformed
        doldur();
        int a = dtm.getRowCount();
        for (int i = 0; i < a; i++) {
            dtm.removeRow(0);
        }
        for (Cicek cicek : cicekler) {
            if (cicek instanceof CansizCicek) {

                Object[] o = {((CansizCicek) cicek).getTür(), ((CansizCicek) cicek).getRenk(), ((CansizCicek) cicek).getFiyat(), ((CansizCicek) cicek).getKategori(), "Cansız", ((CansizCicek) cicek).getMalzeme()};
                dtm.addRow(o);
            } else {
                Object[] o = {cicek.getTür(), cicek.getRenk(), cicek.getFiyat(), cicek.getKategori(), "Canlı", "Doğal"};
                dtm.addRow(o);
            }

        }
        cicekTablosu.setModel(dtm);
        cicekler.removeAll(cicekler);
        ekle.setEnabled(false);
        sil.setEnabled(false);
    }//GEN-LAST:event_hepsiniListeleActionPerformed

    private void kategorilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategorilerActionPerformed

        doldur();
        int a = dtm.getRowCount();
        for (int i = 0; i < a; i++) {
            dtm.removeRow(0);
        }

        for (Cicek cicek : cicekler) {
            if (kategoriler.getSelectedItem().toString().equals(cicek.getKategori()) && !(cicek instanceof CansizCicek)) {
                Object[] o = {cicek.getTür(), cicek.getRenk(), cicek.getFiyat(), cicek.getKategori(), "Canlı", "Doğal"};
                dtm.addRow(o);

            } else if (kategoriler.getSelectedItem().toString().equals(cicek.getKategori()) && (cicek instanceof CansizCicek)) {
                Object[] o = {((CansizCicek) cicek).getTür(), ((CansizCicek) cicek).getRenk(), ((CansizCicek) cicek).getFiyat(), ((CansizCicek) cicek).getKategori(), "Cansız", ((CansizCicek) cicek).getMalzeme()};
                dtm.addRow(o);

            }
        }

        cicekler.removeAll(cicekler);
        ekle.setEnabled(false);
        sil.setEnabled(false);

    }//GEN-LAST:event_kategorilerActionPerformed
    

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed

        adetler.add(adet.getSelectedIndex() + 1);
        dlm.removeAllElements();
        toplamTutar += Integer.parseInt(cicekTablosu.getValueAt(cicekTablosu.getSelectedRow(), 2).toString()) * (adet.getSelectedIndex() + 1);

        siparis.add(new Cicek(cicekTablosu.getValueAt(cicekTablosu.getSelectedRow(), 0).toString(), cicekTablosu.getValueAt(cicekTablosu.getSelectedRow(), 1).toString(), Integer.parseInt(cicekTablosu.getValueAt(cicekTablosu.getSelectedRow(), 2).toString()), cicekTablosu.getValueAt(cicekTablosu.getSelectedRow(), 3).toString()));
        for (Cicek c : siparis) {
            dlm.addElement(adetler.get(siparis.indexOf(c)) + " adet " + c.getRenk() + " " + c.getTür());
        }
        siparisListesi.setModel(dlm);

        tutarEkran.setText(toplamTutar + "");
        ekle.setEnabled(false);
    }//GEN-LAST:event_ekleActionPerformed
    

    private void çıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çıkışActionPerformed
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_çıkışActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        toplamTutar -= adetler.get(siparisListesi.getSelectedIndex()) * siparis.get(siparisListesi.getSelectedIndex()).getFiyat();
        adetler.remove(siparisListesi.getSelectedIndex());
        siparis.remove(siparisListesi.getSelectedIndex());
        dlm.removeAllElements();
        for (Cicek c : siparis) {
            dlm.addElement(adetler.get(siparis.indexOf(c)) + " adet " + c.getRenk() + " " + c.getTür());
        }
        tutarEkran.setText(toplamTutar + " ");
        siparisListesi.setModel(dlm);
        sil.setEnabled(false);
    }//GEN-LAST:event_silActionPerformed

    private void siparisListesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siparisListesiMouseClicked
        sil.setEnabled(true);
    }//GEN-LAST:event_siparisListesiMouseClicked

    private void siparisYonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisYonetimiActionPerformed
        SiparişDeposu depo = new SiparişDeposu(kullanici, adetler, toplamTutar, siparis);
        depo.setVisible(true);
        depo.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_siparisYonetimiActionPerformed

    private void cicekTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cicekTablosuMouseClicked
        ekle.setEnabled(true);
    }//GEN-LAST:event_cicekTablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisAlani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisAlani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisAlani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisAlani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisAlani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adet;
    private javax.swing.JTable cicekTablosu;
    private javax.swing.JButton ekle;
    private javax.swing.JButton hepsiniListele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kategoriler;
    private javax.swing.JButton sil;
    private javax.swing.JList<String> siparisListesi;
    private javax.swing.JButton siparisYonetimi;
    private javax.swing.JTextField tutarEkran;
    private javax.swing.JButton çıkış;
    // End of variables declaration//GEN-END:variables
}
