/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BP2_1821221018_Halis_FurkanAkgulOdev1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmet
 */
public class SiparişDeposu extends javax.swing.JFrame {

    boolean desenkontrol(String aranan, String desen) {
        Pattern p = Pattern.compile(desen);
        Matcher m = p.matcher(aranan);
        return m.find();
    }

    DefaultTableModel dtm = new DefaultTableModel();
    Ekullanici kullanici;
    ArrayList<Integer> adetler = new ArrayList();
    int toplamPara = 0;
    ArrayList<Cicek> siparis = new ArrayList();

    public SiparişDeposu(Ekullanici a, ArrayList<Integer> arr, int t, ArrayList<Cicek> arry) {
        initComponents();
        siparişlerim.setEnabled(false);
        siparisTablosu.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"TÜR", "RENK", "BİRİM FİYAT", "ADET", "KATEGORİ"});
        kullanici = a;
        toplamPara = t;
        for (int i = 0; i < arr.size(); i++) {
            adetler.add(arr.get(i));
        }
        for (int i = 0; i < arry.size(); i++) {
            siparis.add(arry.get(i));
        }
        cicekleriGetir();
        tutarEkran.setText(toplamPara + "");
    }
    
    
    public SiparişDeposu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        siparisTablosu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tutarEkran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bir = new javax.swing.JLabel();
        kartNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        taksitSayisi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adres = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        siparisTamamla = new javax.swing.JButton();
        YeniSipariş = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        siparişlerim = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_fatura = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        siparisTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TÜR", "RENK", "BİRİM FİYAT", "ADET", "KATEGORİ"
            }
        ));
        siparisTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siparisTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(siparisTablosu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("TOPLAM TUTARINIZ:");

        tutarEkran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutarEkranActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Lütfen Kart Bilgilerinizi Giriniz : ");

        bir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bir.setText("Kart No :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("CVV :");

        taksitSayisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "6", "9" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Adres :");

        adres.setColumns(20);
        adres.setRows(5);
        jScrollPane2.setViewportView(adres);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Taksit Sayısı :");

        siparisTamamla.setBackground(new java.awt.Color(102, 255, 51));
        siparisTamamla.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        siparisTamamla.setText("SİPARİŞİ TAMAMLA");
        siparisTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisTamamlaActionPerformed(evt);
            }
        });

        YeniSipariş.setBackground(new java.awt.Color(204, 204, 255));
        YeniSipariş.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        YeniSipariş.setText("YENİ SİPARİŞ");
        YeniSipariş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YeniSiparişActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(YeniSipariş, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(siparisTamamla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tutarEkran, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taksitSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kartNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutarEkran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bir)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taksitSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YeniSipariş)
                    .addComponent(siparisTamamla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEPETİNİZ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("FATURA:");

        jLabel9.setBackground(new java.awt.Color(51, 51, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BP2_1821221018_Halis_FurkanAkgulOdev1/icon/cash-money-icon-design_1692-65_181x108.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("ÇIKIŞ YAP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        siparişlerim.setBackground(new java.awt.Color(255, 204, 0));
        siparişlerim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        siparişlerim.setText("SİPARİŞLERİM");
        siparişlerim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparişlerimActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(txt_fatura);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(siparişlerim, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siparişlerim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siparisTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siparisTablosuMouseClicked

    }//GEN-LAST:event_siparisTablosuMouseClicked

    private void tutarEkranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutarEkranActionPerformed

    }//GEN-LAST:event_tutarEkranActionPerformed

    private void siparisTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisTamamlaActionPerformed
        siparişlerim.setEnabled(true);
        String desen = "[0-9][0-9][0-9]";

        Object o[] = {"Faturanızı Görmek İstiyormusunuz? "};
        if (kartNo.getText().equals("") || adres.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Eksik bilgi girdiniz...", "Lütfen bilgileri kontrol ediniz.", NORMAL);
        } else if (!desenkontrol(cvv.getText(), desen)) {
            JOptionPane.showMessageDialog(this, "CVV kontrol ediniz...", "Eksik bilgi girdiniz...", NORMAL);
        } else if (!desenkontrol(kartNo.getText(), desen)) {
            JOptionPane.showMessageDialog(this, "Kart Numarasınısı kontrol ediniz...", "Eksik bilgi girdiniz...", NORMAL);
        } else {
            try {
                    dosyaYazFatura(kullanici);
                } catch (IOException ex) {
                    Logger.getLogger(SiparişDeposu.class.getName()).log(Level.SEVERE, null, ex);
                }
            int a = JOptionPane.showConfirmDialog(null, o, null, 2, 3);
            if (a == JOptionPane.YES_OPTION) {
                
                try {
                dosyaYazSipariş(kullanici);
            } catch (IOException ex) {
                Logger.getLogger(SiparişDeposu.class.getName()).log(Level.SEVERE, null, ex);
            }
                try {
                    dosyaOkuFatura();
                } catch (IOException ex) {
                    Logger.getLogger(SiparişDeposu.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }

        }
    }//GEN-LAST:event_siparisTamamlaActionPerformed
    public void dosyaYazFatura(Ekullanici a) throws FileNotFoundException, IOException {
        double taksitliFiyat = toplamPara + ((toplamPara / 100) * Integer.parseInt(taksitSayisi.getSelectedItem().toString()));
        String dosya = "c:\\dosyalar\\fatura.txt";
        BufferedWriter bw = new BufferedWriter(new FileWriter(dosya));
        BufferedWriter bwy = new BufferedWriter(new FileWriter(dosya, true));
        bw.write("---------SAYIN--------- " + "\n"
                + "\n"
                + "İSİM: " + kullanici.getAdi() + "\n"
                + "SOYİSİM: " + kullanici.getSoyadi() + " \n"
                + "ADRES: " + adres.getText() + " \n"
                + "TELEFON NUMARASI: " + kullanici.getTelefon() + " \n"
                + "\n" + "---------KART BİLGİLERİ---------" + "\n"
                + "Kredi Kartı No: " + kartNo.getText() + "\n"
                + "Taksit Sayısı: " + taksitSayisi.getSelectedItem().toString() + "\n"
                + "Taksitli Fiyat: " + taksitliFiyat + "TL " + "\n"
                + "Aylık Taksit Tutarı: " + taksitliFiyat / Integer.parseInt(taksitSayisi.getSelectedItem().toString()) + "TL" + "\n" + "\n"
                + "\n"
                + "\n" + "---------SİPARİŞLER---------" + "\n");
        for (Cicek c : siparis) {
            bwy.write(
                    "TÜR: " + c.getTür() + "\n"
                    + "RENK: " + c.getRenk() + "\n"
                    + "RENK: " + c.getFiyat() + "\n"
                    + "KATEGORİ: " + c.getKategori() + "\n"
                    + "\n"
            );
        }
        bw.close();
        bwy.close();
    }

    public void dosyaOkuFatura() throws IOException {
        DefaultListModel dlm = new DefaultListModel();
        txt_fatura.setModel(dlm);
        String s;
        try {
            BufferedReader br = new BufferedReader(new FileReader("c:\\dosyalar\\fatura.txt"));
            while ((s = br.readLine()) != null) {
                dlm.addElement(s);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SiparişDeposu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void dosyaYazSipariş(Ekullanici a) throws FileNotFoundException, IOException {
        String kullanıcıad = a.getKullaniciAdi();
        String dosya = "c:\\dosyalar\\siparis.txt";
        BufferedWriter bw = new BufferedWriter(new FileWriter(dosya, true));
        for (Cicek c : siparis) {
            bw.write("Kullanıcı: " + kullanıcıad + " " + adetler.get(siparis.indexOf(c)) + " adet " + c.getRenk() + " " + c.getTür() + " " + c.getFiyat() + " " + c.getKategori() + " " + "\n");
        }
        bw.close();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login1 = new Login();
        login1.setVisible(true);
        login1.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void siparişlerimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparişlerimActionPerformed
        try {
            Siparislerim s = new Siparislerim(kullanici);
            s.setVisible(true);
            s.setLocationRelativeTo(null);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(SiparişDeposu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siparişlerimActionPerformed

    private void YeniSiparişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YeniSiparişActionPerformed
        SiparisAlani sa = new SiparisAlani(kullanici, siparis, adetler, toplamPara);
        sa.setVisible(true);
        sa.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_YeniSiparişActionPerformed
    public void cicekleriGetir() {
        for (Cicek cicek : siparis) {
            dtm.addRow(new String[]{cicek.getTür(), cicek.getRenk(), String.valueOf(cicek.getFiyat()), String.valueOf(adetler.get(siparis.indexOf(cicek))), cicek.getKategori()});
        }
        siparisTablosu.setModel(dtm);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparişDeposu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparişDeposu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparişDeposu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparişDeposu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparişDeposu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YeniSipariş;
    private javax.swing.JTextArea adres;
    private javax.swing.JLabel bir;
    private javax.swing.JTextField cvv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kartNo;
    private javax.swing.JTable siparisTablosu;
    private javax.swing.JButton siparisTamamla;
    private javax.swing.JButton siparişlerim;
    private javax.swing.JComboBox<String> taksitSayisi;
    private javax.swing.JTextField tutarEkran;
    private javax.swing.JList<String> txt_fatura;
    // End of variables declaration//GEN-END:variables
}
